# Team 09
# Canh Ha An Nguyen 	1098402 	Melbourne
# Ashleigh Armstrong 	1112426 	Melbourne
# Yuanlong Zhang 		772312 	    Melbourne
# Yinsong Chen 		    945600	    Melbourne
# Xiaofu Ning 		    1033578	    Melbourne

---
- name: Clone repo of the project
  git:
    repo: https://github.com/anthailan1702/twitter-analytic.git
    dest: /home/ubuntu/twitter-analytic