---
- name: Add CouchDB GPG key
  shell: "curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc | sudo apt-key add -"

- name: Add CouchDB repository
  shell: 'echo "deb https://apache.bintray.com/couchdb-deb bionic main" | sudo tee -a /etc/apt/sources.list'

- name: Install CouchDB
  apt:
    name: couchdb
    update_cache: yes
    state: present

- name: Mount volume for CouchDB storage
  command: '{{ item }}'
  with_items:
    - 'sudo mkfs.ext4 /dev/vdb'
    - 'sudo mkdir -p /mnt/couchdb'
    - 'sudo mount /dev/vdb /mnt/couchdb'
    - 'sudo chown -R couchdb /mnt/couchdb'

- name: Change admin password and bind address
  lineinfile:
    path: /opt/couchdb/etc/local.ini
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^;bind_address =', line: 'bind_address = 0.0.0.0' }
    - { regexp: '^;admin =', line: 'admin = {{ couchdb_admin_password }}' }

- name: Setup CouchDB as standalone application and change storage directory
  lineinfile:
    path: /opt/couchdb/etc/local.ini
    insertafter: '^\[couchdb\]$'
    line: '{{ item }}'
  with_items:
    - 'single_node=true'
    - 'database_dir=/mnt/couchdb'
    - 'view_index_dir=/mnt/couchdb'

- name: Restart CouchDB
  systemd:
    state: restarted
    daemon_reload: yes
    name: couchdb

- name: Create tweets DB
  command: "curl -X PUT http://admin:{{ couchdb_admin_password }}@127.0.0.1:5984/tweets"