"""
Team 09
Canh Ha An Nguyen 	1098402 	Melbourne
Ashleigh Armstrong 	1112426 	Melbourne
Yuanlong Zhang 		772312 	    Melbourne
Yinsong Chen 		945600	    Melbourne
Xiaofu Ning 		1033578	    Melbourne
"""

---
# This is for testing
#- name: Check out develop
#  command: git checkout develop
#  args:
#    chdir: /home/ubuntu/twitter-analytic

- name: Create a virtual environment
  command: virtualenv venv --python=python3.6
  args:
    chdir: /home/ubuntu/twitter-analytic/crawler
    creates: /home/ubuntu/twitter-analytic/crawler/venv

- name: Install crawler requirements
  pip:
    requirements=/home/ubuntu/twitter-analytic/crawler/requirements.txt
    virtualenv=/home/ubuntu/twitter-analytic/crawler/venv

- name: Copy environment file
  copy:
    src: /Users/annguyen/Documents/UniMelb/Semester2/CC/Assignment/twitter-analytic/crawler/.env
    dest: /home/ubuntu/twitter-analytic/crawler/.env
    owner: ubuntu
    mode: '0644'

- name: Setup crawler info
  command: /home/ubuntu/twitter-analytic/crawler/venv/bin/python /home/ubuntu/twitter-analytic/crawler/populate_info.py

- name: Get running crawler processes
  shell: "ps aux | grep spawn.py | awk '{print $2}'"
  register: running_processes

- name: Kill running crawler processes
  become: yes
  shell: "kill -9 {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"
  ignore_errors: yes

- name: Spawn Covid19 Tweet Crawler
  shell: nohup /home/ubuntu/twitter-analytic/crawler/venv/bin/python /home/ubuntu/twitter-analytic/crawler/spawn.py -g covid19 -d tweets -c keyword &

- name: Spawn Job Crawler
  shell: nohup /home/ubuntu/twitter-analytic/crawler/venv/bin/python /home/ubuntu/twitter-analytic/crawler/spawn.py -g job -d job_tweets -c keyword &

- name: Spawn All Tweet Crawler
  shell: nohup /home/ubuntu/twitter-analytic/crawler/venv/bin/python /home/ubuntu/twitter-analytic/crawler/spawn.py -g all -d all_tweets -c keyword &
