# Team 09
# Canh Ha An Nguyen 	1098402 	Melbourne
# Ashleigh Armstrong 	1112426 	Melbourne
# Yuanlong Zhang 		772312 	    Melbourne
# Yinsong Chen 		    945600	    Melbourne
# Xiaofu Ning 		    1033578	    Melbourne

- hosts: localhost
  vars_files:
    - environment/analytic-server.yml
  gather_facts: true

  roles:
    - role: create-instance

- hosts: analytic-server
  vars_files:
    - environment/analytic-server.yml
  remote_user: ubuntu
  become: yes
  roles:
    - role: setup-unimelb-proxy
    - role: setup-redis
    - role: install-python-dependencies
    - role: clone-project
    - role: setup-analytic-process
