- hosts: localhost
  vars_files:
    - environment/web-server.yml
  gather_facts: true

  roles:
    - role: create-instance

- hosts: web-server
  vars_files:
    - environment/web-server.yml
  remote_user: ubuntu
  become: yes
  roles:
    - role: setup-unimelb-proxy
    - role: install-python-dependencies
    - role: install-node-dependencies
    - role: install-nginx
    - role: clone-project
    - role: setup-backend
    - role: setup-frontend
