---
- name: Install pip
  become: yes
  apt:
    name: python-pip
    update_cache: yes
    state: present

- name: Install pip3
  become: yes
  apt:
    name: python3-pip
    update_cache: yes
    state: present

- name: Install virtualenv
  become: yes
  pip:
    name: virtualenv
