---
- name: Install Redis
  apt:
    name: redis
    update_cache: yes
    state: present

- name: Accept remote connection
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'bind 127.0.0.1 ::1'
    line: 'bind 0.0.0.0 ::1'

- name: Restart Redis
  systemd:
    state: restarted
    daemon_reload: yes
    name: redis