# Team 09
# Canh Ha An Nguyen 	1098402 	Melbourne
# Ashleigh Armstrong 	1112426 	Melbourne
# Yuanlong Zhang 		772312 	    Melbourne
# Yinsong Chen 		    945600	    Melbourne
# Xiaofu Ning 		    1033578	    Melbourne

---
- name: Get the instance
  os_server:
    name: '{{ instance_name }}'
    image: '{{ image_id }}'
    key_name: '{{ key_pair }}'
    flavor: '{{ flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ security_groups }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance

- name: Get/Create a volume
  os_volume:
    display_name: '{{ volume_name }}'
    size: '{{ volume_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present
  register: os_vol

- name: Attach the volume to the instance
  os_server_volume:
    state: present
    server: '{{ instance_name }}'
    volume: '{{ volume_name }}'
