"""
Team 09
Canh Ha An Nguyen 	1098402 	Melbourne
Ashleigh Armstrong 	1112426 	Melbourne
Yuanlong Zhang 		772312 	    Melbourne
Yinsong Chen 		945600	    Melbourne
Xiaofu Ning 		1033578	    Melbourne
"""

#- name: Add Unimelb Proxy
#  lineinfile:
#    dest: /etc/environment
#    line: "{{ item }}"
#  with_items:
#    - "HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
#    - "HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
#    - "http_proxy=http://wwwproxy.unimelb.edu.au:8000/"
#    - "https_proxy=http://wwwproxy.unimelb.edu.au:8000/"
#    - 'no_proxy=“localhost,127.0.0.1,localaddress172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au”'


- name: Add Unimelb Proxy to environment
  copy:
    src: environment
    dest: /etc/environment
    owner: ubuntu
    mode: '0644'